// apps/web/src/app/(admin)/admin/page.tsx
'use client';

import { useState, useEffect, useCallback } from 'react';
import Link from 'next/link';
import {
  List,
  Clock,
  Users,
  Building,
  TrendingUp,
  ArrowUpRight,
  CheckCircle,
  XCircle,
  Loader2,
} from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';
import { Textarea } from '@/components/ui/textarea';
import { api } from '@/lib/api';
import toast from 'react-hot-toast';

interface DashboardStats {
  totalListings: number;
  activeListings: number;
  pendingReview: number;
  totalUsers: number;
  totalSellers: number;
  newUsersThisMonth: number;
  newListingsThisMonth: number;
}

interface PendingListing {
  id: string;
  title: string;
  slug: string;
  price: number;
  priceCurrency: string;
  createdAt: string;
  seller: {
    id: string;
    name: string;
    email: string;
  };
  images: {
    id: string;
    thumbnailUrl: string;
    originalUrl: string;
  }[];
}

const defaultStats: DashboardStats = {
  totalListings: 0,
  activeListings: 0,
  pendingReview: 0,
  totalUsers: 0,
  totalSellers: 0,
  newUsersThisMonth: 0,
  newListingsThisMonth: 0,
};

const chartDaysListings = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
const newListingsData = [45, 38, 62, 51, 73, 28, 19];
const newUsersData = [120, 95, 140, 110, 155, 85, 65];
const maxListings = Math.max(...newListingsData);
const maxUsers = Math.max(...newUsersData);

export default function AdminDashboardPage() {
  const [stats, setStats] = useState<DashboardStats>(defaultStats);
  const [pendingListings, setPendingListings] = useState<PendingListing[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [actionLoading, setActionLoading] = useState<string | null>(null);
  const [rejectModalOpen, setRejectModalOpen] = useState(false);
  const [rejectReason, setRejectReason] = useState('');
  const [rejectingId, setRejectingId] = useState<string | null>(null);

  const fetchDashboard = useCallback(async () => {
    setIsLoading(true);
    try {
      const [dashRes, listingsRes] = await Promise.all([
        api.get<{ success: boolean; data: DashboardStats }>('/admin/dashboard'),
        api.get<{ success: boolean; data: PendingListing[]; pagination: any }>(
          '/admin/listings?status=PENDING_REVIEW&limit=5'
        ),
      ]);
      setStats(dashRes.data);
      setPendingListings(listingsRes.data);
    } catch (err: any) {
      toast.error(err.message || 'Failed to load dashboard');
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchDashboard();
  }, [fetchDashboard]);

  const handleApprove = async (id: string) => {
    setActionLoading(id);
    try {
      await api.patch(`/admin/listings/${id}/approve`);
      toast.success('Listing approved');
      fetchDashboard();
    } catch (err: any) {
      toast.error(err.message || 'Failed to approve listing');
    } finally {
      setActionLoading(null);
    }
  };

  const handleReject = (id: string) => {
    setRejectingId(id);
    setRejectReason('');
    setRejectModalOpen(true);
  };

  const confirmReject = async () => {
    if (!rejectingId) return;
    setActionLoading(rejectingId);
    try {
      await api.patch(`/admin/listings/${rejectingId}/reject`, {
        rejectedReason: rejectReason,
      });
      toast.success('Listing rejected');
      setRejectModalOpen(false);
      setRejectingId(null);
      setRejectReason('');
      fetchDashboard();
    } catch (err: any) {
      toast.error(err.message || 'Failed to reject listing');
    } finally {
      setActionLoading(null);
    }
  };

  const statsCards = [
    {
      title: 'Total Listings',
      value: stats.totalListings.toLocaleString(),
      change: `+${stats.newListingsThisMonth}`,
      icon: List,
      color: 'bg-primary-50 text-primary',
    },
    {
      title: 'Pending Review',
      value: stats.pendingReview.toLocaleString(),
      change: '',
      icon: Clock,
      color: 'bg-yellow-50 text-yellow-600',
    },
    {
      title: 'Total Users',
      value: stats.totalUsers.toLocaleString(),
      change: `+${stats.newUsersThisMonth}`,
      icon: Users,
      color: 'bg-green-50 text-green-600',
    },
    {
      title: 'Total Sellers',
      value: stats.totalSellers.toLocaleString(),
      change: '',
      icon: Building,
      color: 'bg-accent/10 text-accent',
    },
  ];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold text-foreground">Admin Dashboard</h1>
        <p className="text-muted-foreground mt-1">Overview of your marketplace</p>
      </div>

      {/* Stats Cards */}
      {isLoading ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {[1, 2, 3, 4].map((i) => (
            <Card key={i}>
              <CardContent className="pt-5 pb-4">
                <div className="animate-pulse space-y-2">
                  <div className="h-3 w-20 bg-muted rounded" />
                  <div className="h-6 w-16 bg-muted rounded" />
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {statsCards.map((stat) => (
            <Card key={stat.title}>
              <CardContent className="pt-5 pb-4">
                <div className="flex items-start justify-between">
                  <div>
                    <p className="text-xs text-muted-foreground">{stat.title}</p>
                    <p className="text-xl font-bold text-foreground mt-1">{stat.value}</p>
                    {stat.change && (
                      <div className="flex items-center gap-1 mt-1">
                        <ArrowUpRight className="w-3 h-3 text-success" />
                        <span className="text-[10px] text-success">{stat.change} this month</span>
                      </div>
                    )}
                  </div>
                  <div className={`w-9 h-9 rounded-lg ${stat.color} flex items-center justify-center`}>
                    <stat.icon className="w-4 h-4" />
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {/* Charts Row */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* New Listings Chart */}
        <Card>
          <CardHeader className="flex flex-row items-center justify-between">
            <CardTitle className="text-base">New Listings / Day</CardTitle>
            <TrendingUp className="w-4 h-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="flex items-end gap-3 h-40">
              {chartDaysListings.map((day, i) => (
                <div key={day} className="flex-1 flex flex-col items-center gap-1">
                  <div className="w-full bg-muted rounded-t-md relative" style={{ height: '100%' }}>
                    <div
                      className="absolute bottom-0 left-0 right-0 bg-primary/80 rounded-t-md transition-all"
                      style={{ height: `${(newListingsData[i] / maxListings) * 100}%` }}
                    />
                  </div>
                  <span className="text-[10px] text-muted-foreground">{day}</span>
                  <span className="text-[10px] font-medium">{newListingsData[i]}</span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* New Users Chart */}
        <Card>
          <CardHeader className="flex flex-row items-center justify-between">
            <CardTitle className="text-base">New Users / Day</CardTitle>
            <Users className="w-4 h-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="flex items-end gap-3 h-40">
              {chartDaysListings.map((day, i) => (
                <div key={day} className="flex-1 flex flex-col items-center gap-1">
                  <div className="w-full bg-muted rounded-t-md relative" style={{ height: '100%' }}>
                    <div
                      className="absolute bottom-0 left-0 right-0 bg-green-500/80 rounded-t-md transition-all"
                      style={{ height: `${(newUsersData[i] / maxUsers) * 100}%` }}
                    />
                  </div>
                  <span className="text-[10px] text-muted-foreground">{day}</span>
                  <span className="text-[10px] font-medium">{newUsersData[i]}</span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Pending Listings Queue */}
      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <CardTitle className="text-base">Pending Listings</CardTitle>
          <Button variant="ghost" size="sm" asChild>
            <Link href="/admin/listings?status=PENDING_REVIEW">View All</Link>
          </Button>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="py-8 flex items-center justify-center">
              <Loader2 className="w-5 h-5 animate-spin text-muted-foreground" />
              <span className="ml-2 text-sm text-muted-foreground">Loading...</span>
            </div>
          ) : pendingListings.length === 0 ? (
            <div className="py-8 text-center text-muted-foreground">
              <CheckCircle className="w-8 h-8 mx-auto mb-2 text-success" />
              <p className="text-sm">No pending listings to review</p>
            </div>
          ) : (
            <div className="space-y-3">
              {pendingListings.map((listing) => {
                const thumbnail = listing.images?.[0]?.thumbnailUrl || listing.images?.[0]?.originalUrl;
                return (
                  <div
                    key={listing.id}
                    className="flex items-center justify-between gap-4 p-3 rounded-lg bg-muted/30 hover:bg-muted/50 transition-colors"
                  >
                    <div className="flex items-center gap-3 min-w-0">
                      <div className="w-12 h-9 rounded-lg bg-muted overflow-hidden flex items-center justify-center text-muted-foreground text-xs shrink-0">
                        {thumbnail ? (
                          <img src={thumbnail} alt={listing.title} className="w-full h-full object-cover" />
                        ) : (
                          'IMG'
                        )}
                      </div>
                      <div className="min-w-0">
                        <p className="text-sm font-medium text-foreground truncate">{listing.title}</p>
                        <p className="text-xs text-muted-foreground">
                          {listing.seller?.name || '—'} &middot; {listing.priceCurrency || 'EUR'}{' '}
                          {listing.price?.toLocaleString()} &middot;{' '}
                          {new Date(listing.createdAt).toLocaleDateString('en-GB', {
                            day: 'numeric',
                            month: 'short',
                          })}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center gap-2 shrink-0">
                      <Button
                        variant="outline"
                        size="sm"
                        className="text-success border-success/30 hover:bg-success/10"
                        onClick={() => handleApprove(listing.id)}
                        disabled={actionLoading === listing.id}
                      >
                        {actionLoading === listing.id ? (
                          <Loader2 className="w-3.5 h-3.5 mr-1 animate-spin" />
                        ) : (
                          <CheckCircle className="w-3.5 h-3.5 mr-1" />
                        )}
                        Approve
                      </Button>
                      <Button
                        variant="outline"
                        size="sm"
                        className="text-destructive border-destructive/30 hover:bg-destructive/10"
                        onClick={() => handleReject(listing.id)}
                        disabled={actionLoading === listing.id}
                      >
                        <XCircle className="w-3.5 h-3.5 mr-1" />
                        Reject
                      </Button>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Reject Modal */}
      <Dialog open={rejectModalOpen} onOpenChange={setRejectModalOpen}>
        <DialogContent size="sm">
          <DialogHeader>
            <DialogTitle>Reject Listing</DialogTitle>
            <DialogDescription>
              Please provide a reason for rejecting this listing. The seller will be notified.
            </DialogDescription>
          </DialogHeader>
          <Textarea
            placeholder="Enter rejection reason..."
            value={rejectReason}
            onChange={(e) => setRejectReason(e.target.value)}
            rows={4}
          />
          <DialogFooter>
            <Button variant="outline" onClick={() => setRejectModalOpen(false)}>
              Cancel
            </Button>
            <Button
              variant="destructive"
              onClick={confirmReject}
              disabled={!rejectReason.trim() || rejectReason.trim().length < 5 || actionLoading !== null}
            >
              {actionLoading ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Rejecting...
                </>
              ) : (
                'Reject Listing'
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// frontend/app/pages/admin/index.vue
<template>
  <div>
    <h1 class="text-2xl font-bold text-navy mb-8">Admin Dashboard</h1>

    <!-- Stats Cards -->
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
      <div class="bg-white rounded-xl p-6 border border-gray-200">
        <div class="flex items-center justify-between mb-3">
          <div class="w-10 h-10 bg-blue-50 rounded-lg flex items-center justify-center">
            <svg class="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
            </svg>
          </div>
        </div>
        <p class="text-3xl font-bold text-navy">{{ stats.totalListings.toLocaleString() }}</p>
        <p class="text-sm text-gray-500 mt-1">Total Listings</p>
      </div>

      <div class="bg-white rounded-xl p-6 border border-gray-200">
        <div class="flex items-center justify-between mb-3">
          <div class="w-10 h-10 bg-yellow-50 rounded-lg flex items-center justify-center">
            <svg class="w-5 h-5 text-yellow-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </div>
        </div>
        <p class="text-3xl font-bold text-navy">{{ stats.pendingReview }}</p>
        <p class="text-sm text-gray-500 mt-1">Pending Review</p>
      </div>

      <div class="bg-white rounded-xl p-6 border border-gray-200">
        <div class="flex items-center justify-between mb-3">
          <div class="w-10 h-10 bg-green-50 rounded-lg flex items-center justify-center">
            <svg class="w-5 h-5 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
            </svg>
          </div>
        </div>
        <p class="text-3xl font-bold text-navy">{{ stats.totalUsers.toLocaleString() }}</p>
        <p class="text-sm text-gray-500 mt-1">Total Users</p>
      </div>

      <div class="bg-white rounded-xl p-6 border border-gray-200">
        <div class="flex items-center justify-between mb-3">
          <div class="w-10 h-10 bg-orange-lighter rounded-lg flex items-center justify-center">
            <svg class="w-5 h-5 text-orange" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
            </svg>
          </div>
        </div>
        <p class="text-3xl font-bold text-navy">{{ stats.totalSellers }}</p>
        <p class="text-sm text-gray-500 mt-1">Total Sellers</p>
      </div>
    </div>

    <!-- Charts Row -->
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
      <!-- New Listings Chart -->
      <div class="bg-white rounded-xl p-6 border border-gray-200">
        <h2 class="font-bold text-navy mb-4">New Listings (Last 30 Days)</h2>
        <div class="h-64 flex items-end gap-1">
          <div
            v-for="(day, idx) in chartData.listings"
            :key="idx"
            class="flex-1 bg-orange/20 hover:bg-orange/40 rounded-t transition-colors relative group"
            :style="{ height: `${(day.count / maxListingCount) * 100}%`, minHeight: '4px' }"
          >
            <div class="absolute -top-8 left-1/2 -translate-x-1/2 bg-navy text-white text-xs px-2 py-1 rounded opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap">
              {{ day.date }}: {{ day.count }}
            </div>
          </div>
        </div>
        <div class="flex justify-between mt-2 text-xs text-gray-400">
          <span>30 days ago</span>
          <span>Today</span>
        </div>
      </div>

      <!-- New Registrations Chart -->
      <div class="bg-white rounded-xl p-6 border border-gray-200">
        <h2 class="font-bold text-navy mb-4">New Registrations (Last 30 Days)</h2>
        <div class="h-64 flex items-end gap-1">
          <div
            v-for="(day, idx) in chartData.registrations"
            :key="idx"
            class="flex-1 bg-green-200 hover:bg-green-300 rounded-t transition-colors relative group"
            :style="{ height: `${(day.count / maxRegCount) * 100}%`, minHeight: '4px' }"
          >
            <div class="absolute -top-8 left-1/2 -translate-x-1/2 bg-navy text-white text-xs px-2 py-1 rounded opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap">
              {{ day.date }}: {{ day.count }}
            </div>
          </div>
        </div>
        <div class="flex justify-between mt-2 text-xs text-gray-400">
          <span>30 days ago</span>
          <span>Today</span>
        </div>
      </div>
    </div>

    <!-- Pending Listings -->
    <div class="bg-white rounded-xl border border-gray-200">
      <div class="p-6 border-b border-gray-200 flex items-center justify-between">
        <h2 class="font-bold text-navy">Pending Review</h2>
        <NuxtLink to="/admin/listings?status=pending" class="text-sm text-orange hover:text-orange-light font-medium transition-colors">View All</NuxtLink>
      </div>
      <div v-if="!pendingListings.length" class="p-8 text-center text-gray-400">
        <p>No listings pending review</p>
      </div>
      <div v-else class="divide-y divide-gray-100">
        <div v-for="listing in pendingListings" :key="listing.id" class="p-4 flex items-center gap-4 hover:bg-gray-50 transition-colors">
          <div class="w-16 h-12 bg-gray-100 rounded-lg overflow-hidden flex-shrink-0">
            <img v-if="listing.images?.length" :src="listing.images[0].thumbnail" class="w-full h-full object-cover" />
          </div>
          <div class="flex-1 min-w-0">
            <p class="font-medium text-navy text-sm truncate">{{ listing.title }}</p>
            <p class="text-xs text-gray-500">by {{ listing.seller?.name }} &middot; {{ formatDate(listing.created_at) }}</p>
          </div>
          <div class="flex gap-2 flex-shrink-0">
            <button
              @click="approveListing(listing.id)"
              class="px-3 py-1.5 text-xs font-medium bg-green-100 text-green-700 hover:bg-green-200 rounded-lg transition-colors"
            >
              Approve
            </button>
            <button
              @click="openRejectModal(listing)"
              class="px-3 py-1.5 text-xs font-medium bg-red-100 text-red-700 hover:bg-red-200 rounded-lg transition-colors"
            >
              Reject
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Reject Modal -->
    <Teleport to="body">
      <div v-if="showRejectModal" class="fixed inset-0 z-50 flex items-center justify-center">
        <div class="absolute inset-0 bg-black/50" @click="showRejectModal = false" />
        <div class="relative bg-white rounded-xl p-6 max-w-md w-full mx-4">
          <h3 class="text-lg font-bold text-navy mb-4">Reject Listing</h3>
          <textarea
            v-model="rejectReason"
            rows="3"
            placeholder="Reason for rejection..."
            class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:border-orange outline-none text-navy resize-none mb-4"
          />
          <div class="flex gap-3 justify-end">
            <button @click="showRejectModal = false" class="px-4 py-2 text-sm font-medium text-gray-600 hover:text-navy transition-colors">Cancel</button>
            <button @click="rejectListing" class="px-4 py-2 text-sm font-medium bg-red-500 hover:bg-red-600 text-white rounded-lg transition-colors">Reject</button>
          </div>
        </div>
      </div>
    </Teleport>
  </div>
</template>

<script setup lang="ts">
definePageMeta({
  layout: 'admin',
  middleware: 'admin',
})

const { $api } = useNuxtApp()

const stats = reactive({
  totalListings: 0,
  pendingReview: 0,
  totalUsers: 0,
  totalSellers: 0,
})

const chartData = reactive({
  listings: [] as { date: string; count: number }[],
  registrations: [] as { date: string; count: number }[],
})

const pendingListings = ref<any[]>([])
const showRejectModal = ref(false)
const rejectReason = ref('')
const rejectingListingId = ref<number | null>(null)

const maxListingCount = computed(() => Math.max(1, ...chartData.listings.map((d) => d.count)))
const maxRegCount = computed(() => Math.max(1, ...chartData.registrations.map((d) => d.count)))

const formatDate = (date: string) => {
  return new Date(date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
}

onMounted(async () => {
  try {
    const res = await $api<{
      data: {
        total_listings: number
        pending_review: number
        total_users: number
        total_sellers: number
        listings_chart: { date: string; count: number }[]
        registrations_chart: { date: string; count: number }[]
        pending_listings: any[]
      }
    }>('/admin/dashboard')

    stats.totalListings = res.data.total_listings
    stats.pendingReview = res.data.pending_review
    stats.totalUsers = res.data.total_users
    stats.totalSellers = res.data.total_sellers
    chartData.listings = res.data.listings_chart || []
    chartData.registrations = res.data.registrations_chart || []
    pendingListings.value = res.data.pending_listings || []
  } catch {
    // Use defaults
  }
})

const approveListing = async (id: number) => {
  try {
    await $api(`/admin/listings/${id}/approve`, { method: 'POST' })
    pendingListings.value = pendingListings.value.filter((l) => l.id !== id)
    stats.pendingReview = Math.max(0, stats.pendingReview - 1)
  } catch {
    // Error
  }
}

const openRejectModal = (listing: any) => {
  rejectingListingId.value = listing.id
  rejectReason.value = ''
  showRejectModal.value = true
}

const rejectListing = async () => {
  if (!rejectingListingId.value) return
  try {
    await $api(`/admin/listings/${rejectingListingId.value}/reject`, {
      method: 'POST',
      body: { reason: rejectReason.value },
    })
    pendingListings.value = pendingListings.value.filter((l) => l.id !== rejectingListingId.value)
    stats.pendingReview = Math.max(0, stats.pendingReview - 1)
    showRejectModal.value = false
  } catch {
    // Error
  }
}

useHead({
  title: 'Admin Dashboard - MenonTrucks',
})
</script>
