// apps/web/src/components/common/pagination.tsx
'use client';

import * as React from 'react';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import { cn } from '@/lib/utils';

interface PaginationProps {
  currentPage: number;
  totalPages: number;
  onPageChange: (page: number) => void;
  className?: string;
}

function getPageNumbers(currentPage: number, totalPages: number): (number | 'ellipsis')[] {
  const pages: (number | 'ellipsis')[] = [];

  if (totalPages <= 7) {
    for (let i = 1; i <= totalPages; i++) {
      pages.push(i);
    }
    return pages;
  }

  // Always show first page
  pages.push(1);

  if (currentPage > 3) {
    pages.push('ellipsis');
  }

  // Show pages around current
  const start = Math.max(2, currentPage - 1);
  const end = Math.min(totalPages - 1, currentPage + 1);

  for (let i = start; i <= end; i++) {
    pages.push(i);
  }

  if (currentPage < totalPages - 2) {
    pages.push('ellipsis');
  }

  // Always show last page
  pages.push(totalPages);

  return pages;
}

function Pagination({ currentPage, totalPages, onPageChange, className }: PaginationProps) {
  const pages = getPageNumbers(currentPage, totalPages);

  if (totalPages <= 1) return null;

  return (
    <nav
      role="navigation"
      aria-label="Pagination"
      className={cn('flex items-center justify-center gap-1', className)}
    >
      <button
        onClick={() => onPageChange(currentPage - 1)}
        disabled={currentPage <= 1}
        className={cn(
          'inline-flex h-9 w-9 items-center justify-center rounded-lg text-sm transition-colors',
          'hover:bg-muted disabled:pointer-events-none disabled:opacity-50'
        )}
        aria-label="Go to previous page"
      >
        <ChevronLeft className="h-4 w-4" />
      </button>

      {pages.map((page, index) => {
        if (page === 'ellipsis') {
          return (
            <span
              key={`ellipsis-${index}`}
              className="inline-flex h-9 w-9 items-center justify-center text-sm text-muted-foreground"
            >
              ...
            </span>
          );
        }

        return (
          <button
            key={page}
            onClick={() => onPageChange(page)}
            disabled={page === currentPage}
            className={cn(
              'inline-flex h-9 w-9 items-center justify-center rounded-lg text-sm font-medium transition-colors',
              page === currentPage
                ? 'bg-primary text-white'
                : 'hover:bg-muted text-foreground'
            )}
            aria-label={`Go to page ${page}`}
            aria-current={page === currentPage ? 'page' : undefined}
          >
            {page}
          </button>
        );
      })}

      <button
        onClick={() => onPageChange(currentPage + 1)}
        disabled={currentPage >= totalPages}
        className={cn(
          'inline-flex h-9 w-9 items-center justify-center rounded-lg text-sm transition-colors',
          'hover:bg-muted disabled:pointer-events-none disabled:opacity-50'
        )}
        aria-label="Go to next page"
      >
        <ChevronRight className="h-4 w-4" />
      </button>
    </nav>
  );
}

export { Pagination };
export type { PaginationProps };

// frontend/app/components/common/Pagination.vue
<script setup lang="ts">
const props = defineProps<{
  currentPage: number
  totalPages: number
  totalItems: number
}>()

const emit = defineEmits<{
  (e: 'page-change', page: number): void
}>()

const perPage = computed(() => {
  if (props.totalPages <= 0) return props.totalItems
  return Math.ceil(props.totalItems / props.totalPages)
})

const showingFrom = computed(() => {
  if (props.totalItems === 0) return 0
  return (props.currentPage - 1) * perPage.value + 1
})

const showingTo = computed(() => {
  return Math.min(props.currentPage * perPage.value, props.totalItems)
})

const pages = computed(() => {
  const total = props.totalPages
  const current = props.currentPage
  const items: Array<number | 'ellipsis'> = []

  if (total <= 7) {
    for (let i = 1; i <= total; i++) {
      items.push(i)
    }
    return items
  }

  // Always show first page
  items.push(1)

  if (current > 3) {
    items.push('ellipsis')
  }

  // Show pages around current
  const start = Math.max(2, current - 1)
  const end = Math.min(total - 1, current + 1)

  for (let i = start; i <= end; i++) {
    items.push(i)
  }

  if (current < total - 2) {
    items.push('ellipsis')
  }

  // Always show last page
  if (total > 1) {
    items.push(total)
  }

  return items
})

function goToPage(page: number) {
  if (page >= 1 && page <= props.totalPages && page !== props.currentPage) {
    emit('page-change', page)
  }
}
</script>

<template>
  <div v-if="totalPages > 1" class="flex flex-col sm:flex-row items-center justify-between gap-4">
    <!-- Results Info -->
    <p class="text-sm text-gray-500">
      Showing <span class="font-medium text-[#1E2B47]">{{ showingFrom }}</span>-<span class="font-medium text-[#1E2B47]">{{ showingTo }}</span>
      of <span class="font-medium text-[#1E2B47]">{{ totalItems }}</span> results
    </p>

    <!-- Page Buttons -->
    <nav class="flex items-center space-x-1" aria-label="Pagination">
      <!-- Previous -->
      <button
        type="button"
        class="px-3 py-2 text-sm font-medium rounded-lg transition-colors duration-200"
        :class="currentPage === 1
          ? 'text-gray-300 cursor-not-allowed'
          : 'text-[#1E2B47] hover:bg-gray-100'"
        :disabled="currentPage === 1"
        aria-label="Previous page"
        @click="goToPage(currentPage - 1)"
      >
        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
        </svg>
      </button>

      <!-- Page Numbers -->
      <template v-for="(page, index) in pages" :key="index">
        <span
          v-if="page === 'ellipsis'"
          class="px-3 py-2 text-sm text-gray-400"
        >
          ...
        </span>
        <button
          v-else
          type="button"
          class="min-w-[40px] px-3 py-2 text-sm font-medium rounded-lg transition-colors duration-200"
          :class="page === currentPage
            ? 'bg-[#FF6B35] text-white'
            : 'text-[#1E2B47] hover:bg-gray-100'"
          :aria-label="`Page ${page}`"
          :aria-current="page === currentPage ? 'page' : undefined"
          @click="goToPage(page as number)"
        >
          {{ page }}
        </button>
      </template>

      <!-- Next -->
      <button
        type="button"
        class="px-3 py-2 text-sm font-medium rounded-lg transition-colors duration-200"
        :class="currentPage === totalPages
          ? 'text-gray-300 cursor-not-allowed'
          : 'text-[#1E2B47] hover:bg-gray-100'"
        :disabled="currentPage === totalPages"
        aria-label="Next page"
        @click="goToPage(currentPage + 1)"
      >
        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
        </svg>
      </button>
    </nav>
  </div>
</template>
