// apps/web/src/components/common/status-badge.tsx
import * as React from 'react';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils';

type ListingStatus =
  | 'ACTIVE'
  | 'DRAFT'
  | 'PENDING_REVIEW'
  | 'SOLD'
  | 'EXPIRED'
  | 'REJECTED'
  | 'ARCHIVED';

const statusConfig: Record<
  ListingStatus,
  { label: string; className: string }
> = {
  ACTIVE: {
    label: 'Active',
    className: 'bg-green-50 text-green-700 border-green-200',
  },
  DRAFT: {
    label: 'Draft',
    className: 'bg-gray-50 text-gray-700 border-gray-200',
  },
  PENDING_REVIEW: {
    label: 'Pending Review',
    className: 'bg-yellow-50 text-yellow-700 border-yellow-200',
  },
  SOLD: {
    label: 'Sold',
    className: 'bg-blue-50 text-blue-700 border-blue-200',
  },
  EXPIRED: {
    label: 'Expired',
    className: 'bg-red-50 text-red-700 border-red-200',
  },
  REJECTED: {
    label: 'Rejected',
    className: 'bg-red-50 text-red-700 border-red-200',
  },
  ARCHIVED: {
    label: 'Archived',
    className: 'bg-gray-50 text-gray-700 border-gray-200',
  },
};

interface StatusBadgeProps {
  status: ListingStatus;
  className?: string;
}

function StatusBadge({ status, className }: StatusBadgeProps) {
  const config = statusConfig[status];

  return (
    <Badge
      variant="outline"
      className={cn(config.className, className)}
    >
      {config.label}
    </Badge>
  );
}

export { StatusBadge };
export type { StatusBadgeProps, ListingStatus };

// frontend/app/components/common/StatusBadge.vue
<script setup lang="ts">
defineProps<{
  status: 'draft' | 'pending_review' | 'active' | 'sold' | 'expired' | 'rejected'
}>()

const statusConfig: Record<string, { label: string; classes: string }> = {
  draft: {
    label: 'Draft',
    classes: 'bg-gray-100 text-gray-800',
  },
  pending_review: {
    label: 'Pending Review',
    classes: 'bg-yellow-100 text-yellow-800',
  },
  active: {
    label: 'Active',
    classes: 'bg-green-100 text-green-800',
  },
  sold: {
    label: 'Sold',
    classes: 'bg-blue-100 text-blue-800',
  },
  expired: {
    label: 'Expired',
    classes: 'bg-orange-100 text-orange-800',
  },
  rejected: {
    label: 'Rejected',
    classes: 'bg-red-100 text-red-800',
  },
}
</script>

<template>
  <span
    class="inline-flex items-center px-2.5 py-1 text-xs font-medium rounded-full"
    :class="statusConfig[status]?.classes || 'bg-gray-100 text-gray-800'"
  >
    {{ statusConfig[status]?.label || status }}
  </span>
</template>
