// frontend/app/pages/admin/users.vue
<template>
  <div>
    <h1 class="text-2xl font-bold text-navy mb-8">Manage Users</h1>

    <!-- Filters -->
    <div class="flex flex-col sm:flex-row gap-4 mb-6">
      <input
        v-model="searchQuery"
        type="text"
        placeholder="Search by name or email..."
        class="flex-1 px-4 py-2.5 rounded-lg border border-gray-200 focus:border-orange outline-none text-sm text-navy"
        @input="debouncedSearch"
      />
      <select v-model="roleFilter" @change="page = 1; fetchUsers()" class="px-4 py-2.5 rounded-lg border border-gray-200 focus:border-orange outline-none text-sm text-navy">
        <option value="">All Roles</option>
        <option value="buyer">Buyers</option>
        <option value="seller">Sellers</option>
        <option value="admin">Admins</option>
      </select>
    </div>

    <!-- Loading -->
    <div v-if="isLoading" class="bg-white rounded-xl border border-gray-200 p-6">
      <div v-for="i in 10" :key="i" class="flex gap-4 py-3 border-b border-gray-100 animate-pulse">
        <div class="w-10 h-10 bg-gray-200 rounded-full" />
        <div class="flex-1 space-y-2">
          <div class="h-4 bg-gray-200 rounded w-1/3" />
          <div class="h-3 bg-gray-200 rounded w-1/4" />
        </div>
      </div>
    </div>

    <!-- Table -->
    <div v-else class="bg-white rounded-xl border border-gray-200 overflow-hidden">
      <div v-if="!users.length" class="p-12 text-center text-gray-400">
        <p>No users found</p>
      </div>
      <div v-else class="overflow-x-auto">
        <table class="w-full">
          <thead>
            <tr class="border-b border-gray-200 bg-gray-50">
              <th class="text-left py-3 px-4 text-xs font-semibold text-gray-500 uppercase">User</th>
              <th class="text-left py-3 px-4 text-xs font-semibold text-gray-500 uppercase">Email</th>
              <th class="text-left py-3 px-4 text-xs font-semibold text-gray-500 uppercase">Role</th>
              <th class="text-center py-3 px-4 text-xs font-semibold text-gray-500 uppercase">Listings</th>
              <th class="text-left py-3 px-4 text-xs font-semibold text-gray-500 uppercase">Status</th>
              <th class="text-left py-3 px-4 text-xs font-semibold text-gray-500 uppercase">Joined</th>
              <th class="text-right py-3 px-4 text-xs font-semibold text-gray-500 uppercase">Actions</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-100">
            <tr v-for="user in users" :key="user.id" class="hover:bg-gray-50 transition-colors">
              <td class="py-3 px-4">
                <div class="flex items-center gap-3">
                  <div class="w-8 h-8 rounded-full bg-navy flex items-center justify-center text-white text-xs font-semibold flex-shrink-0">
                    {{ user.name.charAt(0).toUpperCase() }}
                  </div>
                  <span class="text-sm font-medium text-navy">{{ user.name }}</span>
                </div>
              </td>
              <td class="py-3 px-4">
                <span class="text-sm text-gray-600">{{ user.email }}</span>
              </td>
              <td class="py-3 px-4">
                <span :class="roleBadge(user.role)" class="px-2.5 py-0.5 rounded-full text-xs font-medium capitalize">{{ user.role }}</span>
              </td>
              <td class="py-3 px-4 text-center">
                <span class="text-sm text-gray-600">{{ user.listings_count || 0 }}</span>
              </td>
              <td class="py-3 px-4">
                <span :class="user.is_active ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'" class="px-2.5 py-0.5 rounded-full text-xs font-medium">
                  {{ user.is_active ? 'Active' : 'Inactive' }}
                </span>
              </td>
              <td class="py-3 px-4">
                <span class="text-sm text-gray-500">{{ formatDate(user.created_at) }}</span>
              </td>
              <td class="py-3 px-4">
                <div class="flex items-center justify-end gap-2">
                  <button
                    @click="toggleUserStatus(user)"
                    :class="user.is_active ? 'text-red-400 hover:text-red-600' : 'text-green-400 hover:text-green-600'"
                    class="transition-colors"
                    :title="user.is_active ? 'Deactivate' : 'Activate'"
                  >
                    <svg v-if="user.is_active" class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636" />
                    </svg>
                    <svg v-else class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                  </button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <!-- Pagination -->
      <div v-if="lastPage > 1" class="flex items-center justify-between px-4 py-3 border-t border-gray-200 bg-gray-50">
        <p class="text-sm text-gray-500">Page {{ page }} of {{ lastPage }} ({{ total }} users)</p>
        <div class="flex gap-2">
          <button @click="page--" :disabled="page === 1" class="px-3 py-1 text-sm rounded border border-gray-200 disabled:opacity-50 hover:border-orange transition-colors">Prev</button>
          <button @click="page++" :disabled="page === lastPage" class="px-3 py-1 text-sm rounded border border-gray-200 disabled:opacity-50 hover:border-orange transition-colors">Next</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
definePageMeta({
  layout: 'admin',
  middleware: 'admin',
})

const { $api } = useNuxtApp()

interface AdminUser {
  id: number
  name: string
  email: string
  role: string
  listings_count: number
  is_active: boolean
  created_at: string
}

const users = ref<AdminUser[]>([])
const isLoading = ref(true)
const page = ref(1)
const lastPage = ref(1)
const total = ref(0)
const searchQuery = ref('')
const roleFilter = ref('')

let debounceTimer: ReturnType<typeof setTimeout> | null = null

const debouncedSearch = () => {
  if (debounceTimer) clearTimeout(debounceTimer)
  debounceTimer = setTimeout(() => {
    page.value = 1
    fetchUsers()
  }, 300)
}

const roleBadge = (role: string) => {
  const map: Record<string, string> = {
    buyer: 'bg-blue-100 text-blue-700',
    seller: 'bg-orange-lighter text-orange',
    admin: 'bg-red-100 text-red-700',
  }
  return map[role] || 'bg-gray-100 text-gray-700'
}

const formatDate = (date: string) => new Date(date).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })

const fetchUsers = async () => {
  isLoading.value = true
  try {
    const params: Record<string, unknown> = { page: page.value }
    if (searchQuery.value) params.search = searchQuery.value
    if (roleFilter.value) params.role = roleFilter.value
    const res = await $api<{ data: AdminUser[]; meta: { last_page: number; total: number } }>('/admin/users', { params })
    users.value = res.data
    lastPage.value = res.meta.last_page
    total.value = res.meta.total
  } catch {
    users.value = []
  } finally {
    isLoading.value = false
  }
}

const toggleUserStatus = async (user: AdminUser) => {
  try {
    await $api(`/admin/users/${user.id}/toggle-status`, { method: 'POST' })
    user.is_active = !user.is_active
  } catch {
    // Error
  }
}

watch(page, () => fetchUsers())
onMounted(() => fetchUsers())

useHead({ title: 'Manage Users - Admin - MenonTrucks' })
</script>

// apps/web/src/app/(admin)/admin/users/page.tsx
'use client';

import { useState } from 'react';
import {
  Search,
  Shield,
  ShieldOff,
  MoreVertical,
  UserCircle,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Pagination } from '@/components/common/pagination';
import { cn } from '@/lib/utils';

interface AdminUser {
  id: string;
  name: string;
  email: string;
  role: 'BUYER' | 'SELLER' | 'ADMIN';
  avatar: string;
  listingsCount: number;
  status: 'active' | 'banned';
  joinedAt: string;
}

const roleColors: Record<string, string> = {
  BUYER: 'bg-blue-50 text-blue-700 border-blue-200',
  SELLER: 'bg-green-50 text-green-700 border-green-200',
  ADMIN: 'bg-red-50 text-red-700 border-red-200',
};

const dummyUsers: AdminUser[] = [
  { id: '1', name: 'Jan de Vries', email: 'jan@transeuropa.nl', role: 'SELLER', avatar: '', listingsCount: 24, status: 'active', joinedAt: '2023-06-15' },
  { id: '2', name: 'Klaus Mueller', email: 'klaus@nordic-trucks.de', role: 'SELLER', avatar: '', listingsCount: 45, status: 'active', joinedAt: '2023-03-20' },
  { id: '3', name: 'Pierre Dupont', email: 'pierre.dupont@gmail.com', role: 'BUYER', avatar: '', listingsCount: 0, status: 'active', joinedAt: '2024-01-05' },
  { id: '4', name: 'Anna Kowalski', email: 'anna@fleetpro.be', role: 'SELLER', avatar: '', listingsCount: 18, status: 'active', joinedAt: '2023-08-10' },
  { id: '5', name: 'Marco Rossi', email: 'marco.rossi@email.it', role: 'BUYER', avatar: '', listingsCount: 0, status: 'banned', joinedAt: '2023-11-22' },
  { id: '6', name: 'Sarah Johnson', email: 'sarah.j@menontrucks.com', role: 'ADMIN', avatar: '', listingsCount: 0, status: 'active', joinedAt: '2023-01-01' },
  { id: '7', name: 'Johan Svensson', email: 'johan@sventruck.se', role: 'SELLER', avatar: '', listingsCount: 12, status: 'active', joinedAt: '2023-09-18' },
  { id: '8', name: 'Elena Garcia', email: 'elena.garcia@email.es', role: 'BUYER', avatar: '', listingsCount: 0, status: 'active', joinedAt: '2024-01-12' },
  { id: '9', name: 'Thomas Brandt', email: 'thomas@bavaria-truck.de', role: 'SELLER', avatar: '', listingsCount: 67, status: 'active', joinedAt: '2023-02-14' },
  { id: '10', name: 'Lucca Bianchi', email: 'lucca@italtruck.it', role: 'SELLER', avatar: '', listingsCount: 8, status: 'active', joinedAt: '2023-12-01' },
];

export default function AdminUsersPage() {
  const [searchQuery, setSearchQuery] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const [openMenu, setOpenMenu] = useState<string | null>(null);

  const filteredUsers = dummyUsers.filter(
    (user) =>
      user.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      user.email.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-foreground">User Management</h1>
        <p className="text-muted-foreground mt-1">
          Manage users and their permissions ({dummyUsers.length} total users)
        </p>
      </div>

      {/* Search */}
      <div className="relative">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
        <input
          type="text"
          placeholder="Search by name or email..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="w-full max-w-md h-10 pl-10 pr-4 rounded-lg border border-border bg-white text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary"
        />
      </div>

      {/* Table */}
      <Card>
        <CardContent className="p-0">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-border bg-muted/30">
                  <th className="text-left py-3 px-4 text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                    User
                  </th>
                  <th className="text-left py-3 px-4 text-xs font-semibold text-muted-foreground uppercase tracking-wider hidden sm:table-cell">
                    Email
                  </th>
                  <th className="text-left py-3 px-4 text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                    Role
                  </th>
                  <th className="text-right py-3 px-4 text-xs font-semibold text-muted-foreground uppercase tracking-wider hidden md:table-cell">
                    Listings
                  </th>
                  <th className="text-left py-3 px-4 text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                    Status
                  </th>
                  <th className="text-left py-3 px-4 text-xs font-semibold text-muted-foreground uppercase tracking-wider hidden lg:table-cell">
                    Joined
                  </th>
                  <th className="py-3 px-4 text-xs font-semibold text-muted-foreground uppercase tracking-wider text-right">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody>
                {filteredUsers.map((user) => (
                  <tr key={user.id} className="border-b border-border last:border-0 hover:bg-muted/20 transition-colors">
                    <td className="py-3 px-4">
                      <div className="flex items-center gap-3">
                        <div className="w-9 h-9 rounded-full bg-primary-50 flex items-center justify-center shrink-0">
                          <span className="text-sm font-semibold text-primary">
                            {user.name.charAt(0)}
                          </span>
                        </div>
                        <span className="text-sm font-medium text-foreground">{user.name}</span>
                      </div>
                    </td>
                    <td className="py-3 px-4 hidden sm:table-cell">
                      <span className="text-sm text-muted-foreground">{user.email}</span>
                    </td>
                    <td className="py-3 px-4">
                      <Badge variant="outline" className={roleColors[user.role]}>
                        {user.role}
                      </Badge>
                    </td>
                    <td className="py-3 px-4 text-right hidden md:table-cell">
                      <span className="text-sm text-foreground">{user.listingsCount}</span>
                    </td>
                    <td className="py-3 px-4">
                      <Badge
                        variant={user.status === 'active' ? 'success' : 'danger'}
                        className="capitalize"
                      >
                        {user.status}
                      </Badge>
                    </td>
                    <td className="py-3 px-4 hidden lg:table-cell">
                      <span className="text-sm text-muted-foreground">
                        {new Date(user.joinedAt).toLocaleDateString('en-GB', {
                          day: 'numeric',
                          month: 'short',
                          year: 'numeric',
                        })}
                      </span>
                    </td>
                    <td className="py-3 px-4">
                      <div className="flex items-center justify-end gap-1">
                        {user.role !== 'ADMIN' && (
                          <Button
                            variant="ghost"
                            size="sm"
                            className={cn(
                              'h-8 px-2',
                              user.status === 'active'
                                ? 'text-destructive hover:text-destructive'
                                : 'text-success hover:text-success'
                            )}
                            title={user.status === 'active' ? 'Ban User' : 'Activate User'}
                          >
                            {user.status === 'active' ? (
                              <ShieldOff className="w-4 h-4" />
                            ) : (
                              <Shield className="w-4 h-4" />
                            )}
                          </Button>
                        )}
                        <div className="relative">
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-8 px-2"
                            onClick={() => setOpenMenu(openMenu === user.id ? null : user.id)}
                          >
                            <MoreVertical className="w-4 h-4" />
                          </Button>
                          {openMenu === user.id && (
                            <div className="absolute right-0 top-full mt-1 bg-white rounded-lg shadow-lg border border-border z-10 py-1 min-w-[140px]">
                              <button
                                className="flex items-center gap-2 w-full px-3 py-2 text-sm text-foreground hover:bg-muted transition-colors"
                                onClick={() => setOpenMenu(null)}
                              >
                                <UserCircle className="w-4 h-4" />
                                View Profile
                              </button>
                              <button
                                className="flex items-center gap-2 w-full px-3 py-2 text-sm text-foreground hover:bg-muted transition-colors"
                                onClick={() => setOpenMenu(null)}
                              >
                                <Shield className="w-4 h-4" />
                                Change Role
                              </button>
                            </div>
                          )}
                        </div>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          {filteredUsers.length === 0 && (
            <div className="py-12 text-center text-muted-foreground">
              <p className="text-sm">No users found</p>
            </div>
          )}
        </CardContent>
      </Card>

      <Pagination currentPage={currentPage} totalPages={5} onPageChange={setCurrentPage} />
    </div>
  );
}
