// frontend/app/pages/seller/profile.vue
<template>
  <div>
    <h1 class="text-2xl font-bold text-navy mb-2">Seller Profile</h1>
    <p class="text-gray-500 mb-8">Manage your public seller information</p>

    <!-- Success Message -->
    <div v-if="successMessage" class="mb-6 bg-green-50 border border-green-200 text-green-700 px-4 py-3 rounded-lg text-sm flex items-center gap-2">
      <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" /></svg>
      {{ successMessage }}
    </div>

    <div class="bg-white rounded-xl border border-gray-200 p-6 lg:p-8">
      <!-- Logo Upload -->
      <div class="mb-8">
        <label class="block text-sm font-medium text-navy mb-3">Company Logo</label>
        <div class="flex items-center gap-6">
          <div class="w-24 h-24 rounded-xl bg-gray-100 flex items-center justify-center overflow-hidden border-2 border-gray-200">
            <img v-if="logoPreview || form.avatar" :src="logoPreview || form.avatar" class="w-full h-full object-cover" />
            <svg v-else class="w-10 h-10 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
            </svg>
          </div>
          <div>
            <button @click="logoInput?.click()" class="bg-gray-100 hover:bg-gray-200 text-navy px-4 py-2 rounded-lg text-sm font-medium transition-colors">
              Upload Logo
            </button>
            <input ref="logoInput" type="file" accept="image/*" class="hidden" @change="handleLogoSelect" />
            <p class="text-xs text-gray-400 mt-2">PNG, JPG. Recommended 200x200px.</p>
          </div>
        </div>
      </div>

      <form @submit.prevent="handleSave" class="space-y-6">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div class="md:col-span-2">
            <label class="block text-sm font-medium text-navy mb-1.5">Company Name *</label>
            <input v-model="form.company" type="text" class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:border-orange outline-none text-navy" placeholder="Your company name" />
          </div>
          <div class="md:col-span-2">
            <label class="block text-sm font-medium text-navy mb-1.5">Description</label>
            <textarea v-model="form.description" rows="4" class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:border-orange outline-none text-navy resize-none" placeholder="Tell buyers about your business..." />
          </div>
          <div>
            <label class="block text-sm font-medium text-navy mb-1.5">Website</label>
            <input v-model="form.website" type="url" class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:border-orange outline-none text-navy" placeholder="https://www.example.com" />
          </div>
          <div>
            <label class="block text-sm font-medium text-navy mb-1.5">Phone</label>
            <input v-model="form.phone" type="tel" class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:border-orange outline-none text-navy" placeholder="+49 123 456 789" />
          </div>
          <div class="md:col-span-2">
            <label class="block text-sm font-medium text-navy mb-1.5">Address</label>
            <input v-model="form.address" type="text" class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:border-orange outline-none text-navy" placeholder="Street address" />
          </div>
          <div>
            <label class="block text-sm font-medium text-navy mb-1.5">City</label>
            <input v-model="form.city" type="text" class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:border-orange outline-none text-navy" placeholder="City" />
          </div>
          <div>
            <label class="block text-sm font-medium text-navy mb-1.5">Region / State</label>
            <input v-model="form.region" type="text" class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:border-orange outline-none text-navy" placeholder="Region" />
          </div>
          <div>
            <label class="block text-sm font-medium text-navy mb-1.5">Country *</label>
            <input v-model="form.country" type="text" class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:border-orange outline-none text-navy" placeholder="Country" />
          </div>
        </div>

        <div class="flex justify-end pt-4 border-t border-gray-200">
          <button
            type="submit"
            :disabled="isSaving"
            class="bg-orange hover:bg-orange-light text-white px-8 py-3 rounded-lg font-semibold transition-colors disabled:opacity-50"
          >
            {{ isSaving ? 'Saving...' : 'Save Profile' }}
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
definePageMeta({
  layout: 'seller',
  middleware: 'seller',
})

const { $api } = useNuxtApp()

const isSaving = ref(false)
const successMessage = ref('')
const logoInput = ref<HTMLInputElement | null>(null)
const logoPreview = ref('')
const logoFile = ref<File | null>(null)

const form = reactive({
  company: '',
  description: '',
  website: '',
  phone: '',
  address: '',
  city: '',
  region: '',
  country: '',
  avatar: '',
})

// Load profile
onMounted(async () => {
  try {
    const res = await $api<{ data: any }>('/seller/profile')
    const p = res.data
    form.company = p.company || ''
    form.description = p.description || ''
    form.website = p.website || ''
    form.phone = p.phone || ''
    form.address = p.address || ''
    form.city = p.city || ''
    form.region = p.region || ''
    form.country = p.country || ''
    form.avatar = p.avatar || ''
  } catch {
    // Use defaults
  }
})

const handleLogoSelect = (e: Event) => {
  const target = e.target as HTMLInputElement
  const file = target.files?.[0]
  if (!file) return
  logoFile.value = file
  const reader = new FileReader()
  reader.onload = (ev) => {
    logoPreview.value = ev.target?.result as string
  }
  reader.readAsDataURL(file)
}

const handleSave = async () => {
  isSaving.value = true
  successMessage.value = ''
  try {
    // Upload logo first if changed
    if (logoFile.value) {
      const formData = new FormData()
      formData.append('avatar', logoFile.value)
      await $api('/seller/profile/avatar', { method: 'POST', body: formData })
    }

    await $api('/seller/profile', {
      method: 'PUT',
      body: {
        company: form.company,
        description: form.description,
        website: form.website,
        phone: form.phone,
        address: form.address,
        city: form.city,
        region: form.region,
        country: form.country,
      },
    })

    successMessage.value = 'Profile updated successfully!'
    setTimeout(() => { successMessage.value = '' }, 3000)
  } catch {
    // Error handled
  } finally {
    isSaving.value = false
  }
}

useHead({
  title: 'Seller Profile - MenonTrucks',
})
</script>

// apps/web/src/app/(seller)/seller/profile/page.tsx
'use client';

import { useState } from 'react';
import { Upload, Save, Building } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

const countryOptions = [
  'Netherlands', 'Germany', 'Belgium', 'France', 'Poland', 'Spain', 'Italy',
  'United Kingdom', 'Czech Republic', 'Austria', 'Sweden', 'Denmark',
];

export default function SellerProfilePage() {
  const [formData, setFormData] = useState({
    companyName: 'TransEuropa BV',
    description: 'TransEuropa BV is one of the leading commercial vehicle dealers in the Netherlands, specializing in trucks and tractor units from major manufacturers worldwide.',
    website: 'https://transeuropa.nl',
    phone: '+31 10 123 4567',
    address: 'Industrieweg 45',
    city: 'Rotterdam',
    region: 'South Holland',
    country: 'netherlands',
    postalCode: '3045 AH',
  });
  const [isSaving, setIsSaving] = useState(false);
  const [saved, setSaved] = useState(false);

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>
  ) => {
    setFormData((prev) => ({ ...prev, [e.target.name]: e.target.value }));
    setSaved(false);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSaving(true);
    // Simulate API call
    await new Promise((resolve) => setTimeout(resolve, 1000));
    setIsSaving(false);
    setSaved(true);
  };

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-foreground">Company Profile</h1>
        <p className="text-muted-foreground mt-1">
          Update your company information visible to buyers
        </p>
      </div>

      <form onSubmit={handleSubmit} className="space-y-6">
        {/* Logo Upload */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base flex items-center gap-2">
              <Building className="w-5 h-5" />
              Company Logo
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-center gap-6">
              <div className="w-24 h-24 rounded-xl bg-muted flex items-center justify-center text-muted-foreground border-2 border-dashed border-border">
                <span className="text-3xl font-bold text-primary">
                  {formData.companyName.charAt(0)}
                </span>
              </div>
              <div>
                <Button type="button" variant="outline" size="sm">
                  <Upload className="w-4 h-4 mr-2" />
                  Upload Logo
                </Button>
                <p className="text-xs text-muted-foreground mt-2">
                  Recommended: 200x200px, JPG or PNG, max 2MB
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Company Details */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Company Details</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <Input
              id="companyName"
              name="companyName"
              label="Company Name"
              value={formData.companyName}
              onChange={handleChange}
              required
            />
            <Textarea
              id="description"
              name="description"
              label="Description"
              placeholder="Tell buyers about your company..."
              value={formData.description}
              onChange={handleChange}
              rows={5}
              showCharCount
              maxLength={2000}
            />
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <Input
                id="website"
                name="website"
                label="Website"
                placeholder="https://yourcompany.com"
                value={formData.website}
                onChange={handleChange}
              />
              <Input
                id="phone"
                name="phone"
                label="Phone"
                placeholder="+31 10 123 4567"
                value={formData.phone}
                onChange={handleChange}
              />
            </div>
          </CardContent>
        </Card>

        {/* Address */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Address</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <Input
              id="address"
              name="address"
              label="Street Address"
              placeholder="Industrieweg 45"
              value={formData.address}
              onChange={handleChange}
            />
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              <Input
                id="city"
                name="city"
                label="City"
                placeholder="Rotterdam"
                value={formData.city}
                onChange={handleChange}
              />
              <Input
                id="region"
                name="region"
                label="Region / State"
                placeholder="South Holland"
                value={formData.region}
                onChange={handleChange}
              />
              <Input
                id="postalCode"
                name="postalCode"
                label="Postal Code"
                placeholder="3045 AH"
                value={formData.postalCode}
                onChange={handleChange}
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-foreground mb-1.5">Country</label>
              <select
                name="country"
                value={formData.country}
                onChange={handleChange}
                className="flex h-10 w-full rounded-lg border border-input bg-white px-3 py-2 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
              >
                <option value="">Select country...</option>
                {countryOptions.map((c) => (
                  <option key={c} value={c.toLowerCase()}>{c}</option>
                ))}
              </select>
            </div>
          </CardContent>
        </Card>

        {/* Save */}
        <div className="flex items-center justify-between">
          {saved && (
            <p className="text-sm text-success font-medium">Profile saved successfully!</p>
          )}
          {!saved && <div />}
          <Button type="submit" variant="accent" disabled={isSaving}>
            {isSaving ? (
              <>
                <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin mr-2" />
                Saving...
              </>
            ) : (
              <>
                <Save className="w-4 h-4 mr-2" />
                Save Profile
              </>
            )}
          </Button>
        </div>
      </form>
    </div>
  );
}
