// frontend/app/components/common/ListingCard.vue
<script setup lang="ts">
interface Listing {
  id: number | string
  title: string
  slug: string
  category_slug: string
  price: number | null
  price_on_request: boolean
  year: number | null
  mileage_km: number | null
  fuel_type: string | null
  location: string | null
  image_url: string | null
  condition: 'New' | 'Used' | string
  brand_name: string | null
  is_featured: boolean
  seller_name: string | null
}

const props = defineProps<{
  listing: Listing
}>()

const emit = defineEmits<{
  (e: 'toggle-favorite', id: number | string): void
}>()

const isFavorited = ref(false)

const formattedPrice = computed(() => {
  if (props.listing.price_on_request || !props.listing.price) {
    return 'Price on request'
  }
  return new Intl.NumberFormat('en-EU', {
    style: 'currency',
    currency: 'EUR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(props.listing.price)
})

const formattedMileage = computed(() => {
  if (!props.listing.mileage_km) return null
  return `${new Intl.NumberFormat('en').format(props.listing.mileage_km)} km`
})

const conditionBadgeClass = computed(() => {
  return props.listing.condition === 'New'
    ? 'bg-green-500 text-white'
    : 'bg-gray-500 text-white'
})

const listingUrl = computed(() => {
  return `/${props.listing.category_slug}/${props.listing.slug}`
})

function toggleFavorite(event: Event) {
  event.preventDefault()
  event.stopPropagation()
  isFavorited.value = !isFavorited.value
  emit('toggle-favorite', props.listing.id)
}
</script>

<template>
  <NuxtLink
    :to="listingUrl"
    class="block bg-white rounded-xl shadow-sm hover:shadow-md transition-shadow duration-300 overflow-hidden group"
  >
    <!-- Image Section -->
    <div class="relative aspect-[4/3] overflow-hidden">
      <img
        v-if="listing.image_url"
        :src="listing.image_url"
        :alt="listing.title"
        class="w-full h-full object-cover rounded-t-xl group-hover:scale-105 transition-transform duration-300"
        loading="lazy"
      />
      <div
        v-else
        class="w-full h-full bg-gray-200 flex items-center justify-center rounded-t-xl"
      >
        <svg class="w-16 h-16 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="1.5"
            d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"
          />
        </svg>
      </div>

      <!-- Featured Badge -->
      <span
        v-if="listing.is_featured"
        class="absolute top-3 left-3 bg-[#FF6B35] text-white text-xs font-semibold px-2.5 py-1 rounded-full"
      >
        Featured
      </span>

      <!-- Condition Badge -->
      <span
        v-if="listing.condition"
        class="absolute top-3 right-12 text-xs font-semibold px-2.5 py-1 rounded-full"
        :class="conditionBadgeClass"
      >
        {{ listing.condition }}
      </span>

      <!-- Favorite Button -->
      <button
        type="button"
        class="absolute top-3 right-3 w-8 h-8 flex items-center justify-center rounded-full bg-white/80 hover:bg-white transition-colors duration-200"
        :aria-label="isFavorited ? 'Remove from favorites' : 'Add to favorites'"
        @click="toggleFavorite"
      >
        <svg
          class="w-5 h-5 transition-colors duration-200"
          :class="isFavorited ? 'text-red-500 fill-red-500' : 'text-gray-600'"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"
            :fill="isFavorited ? 'currentColor' : 'none'"
          />
        </svg>
      </button>
    </div>

    <!-- Content Section -->
    <div class="p-4">
      <!-- Title -->
      <h3 class="font-semibold text-[#1E2B47] text-sm leading-snug line-clamp-2 mb-2">
        {{ listing.title }}
      </h3>

      <!-- Price -->
      <p
        class="text-xl font-bold mb-3"
        :class="listing.price_on_request || !listing.price ? 'text-gray-500 text-base' : 'text-[#FF6B35]'"
      >
        {{ formattedPrice }}
      </p>

      <!-- Specs Row -->
      <div class="flex items-center text-xs text-gray-500 space-x-2 mb-2">
        <span v-if="listing.year">{{ listing.year }}</span>
        <span v-if="listing.year && formattedMileage" class="text-gray-300">|</span>
        <span v-if="formattedMileage">{{ formattedMileage }}</span>
        <span v-if="(listing.year || formattedMileage) && listing.fuel_type" class="text-gray-300">|</span>
        <span v-if="listing.fuel_type">{{ listing.fuel_type }}</span>
      </div>

      <!-- Location -->
      <div v-if="listing.location" class="flex items-center text-xs text-gray-500 mb-2">
        <svg class="w-3.5 h-3.5 mr-1 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"
          />
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"
          />
        </svg>
        <span class="truncate">{{ listing.location }}</span>
      </div>

      <!-- Seller Name -->
      <p v-if="listing.seller_name" class="text-xs text-gray-400 truncate">
        {{ listing.seller_name }}
      </p>
    </div>
  </NuxtLink>
</template>

// apps/web/src/components/listings/listing-card.tsx
'use client';

import React from 'react';
import Link from 'next/link';
import { Heart, MapPin, Calendar, Gauge, Fuel } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { useFavoritesStore } from '@/store/favorites';
import { cn } from '@/lib/utils';

export interface ListingCardData {
  id: string;
  slug: string;
  title: string;
  price: number | null;
  currency?: string;
  condition: 'NEW' | 'USED';
  images: string[];
  year: number;
  mileage?: number;
  fuelType?: string;
  location: {
    city: string;
    country: string;
  };
  seller: {
    name: string;
  };
  isFeatured?: boolean;
}

interface ListingCardProps {
  listing: ListingCardData;
  view?: 'grid' | 'list';
}

export function ListingCard({ listing, view = 'grid' }: ListingCardProps) {
  const { toggleFavorite, isFavorited } = useFavoritesStore();
  const favorited = isFavorited(listing.id);

  const handleFavoriteClick = (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    toggleFavorite(listing.id);
  };

  const formattedPrice = listing.price
    ? new Intl.NumberFormat('en-EU', {
        style: 'currency',
        currency: listing.currency || 'EUR',
        maximumFractionDigits: 0,
      }).format(listing.price)
    : null;

  if (view === 'list') {
    return (
      <Link href={`/listings/${listing.slug}`} className="block group">
        <div className="flex gap-4 bg-white rounded-xl border border-border p-3 hover:shadow-md transition-shadow">
          <div className="relative w-64 h-44 flex-shrink-0 rounded-lg overflow-hidden bg-muted">
            {listing.images[0] ? (
              <img
                src={listing.images[0]}
                alt={listing.title}
                className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
              />
            ) : (
              <div className="w-full h-full flex items-center justify-center text-muted-foreground">
                <Gauge className="w-12 h-12" />
              </div>
            )}
            {listing.isFeatured && (
              <Badge className="absolute top-2 left-2 bg-accent text-white border-0">
                Featured
              </Badge>
            )}
            <Badge
              variant={listing.condition === 'NEW' ? 'success' : 'secondary'}
              className="absolute top-2 right-2"
            >
              {listing.condition === 'NEW' ? 'New' : 'Used'}
            </Badge>
          </div>
          <div className="flex-1 flex flex-col justify-between py-1">
            <div>
              <h3 className="font-semibold text-foreground group-hover:text-primary transition-colors line-clamp-1 text-base">
                {listing.title}
              </h3>
              <div className="flex items-center gap-3 mt-2 text-sm text-muted-foreground">
                <span className="flex items-center gap-1">
                  <Calendar className="w-3.5 h-3.5" />
                  {listing.year}
                </span>
                {listing.mileage != null && (
                  <span className="flex items-center gap-1">
                    <Gauge className="w-3.5 h-3.5" />
                    {listing.mileage.toLocaleString()} km
                  </span>
                )}
                {listing.fuelType && (
                  <span className="flex items-center gap-1">
                    <Fuel className="w-3.5 h-3.5" />
                    {listing.fuelType}
                  </span>
                )}
              </div>
              <div className="flex items-center gap-1 mt-2 text-sm text-muted-foreground">
                <MapPin className="w-3.5 h-3.5" />
                {listing.location.city}, {listing.location.country}
              </div>
            </div>
            <div className="flex items-center justify-between">
              <p className="text-lg font-bold text-accent">
                {formattedPrice || 'Price on request'}
              </p>
              <p className="text-xs text-muted-foreground">{listing.seller.name}</p>
            </div>
          </div>
          <button
            onClick={handleFavoriteClick}
            className="self-start p-2 rounded-full hover:bg-muted transition-colors"
          >
            <Heart
              className={cn(
                'w-5 h-5 transition-colors',
                favorited ? 'fill-red-500 text-red-500' : 'text-muted-foreground'
              )}
            />
          </button>
        </div>
      </Link>
    );
  }

  return (
    <Link href={`/listings/${listing.slug}`} className="block group">
      <div className="bg-white rounded-xl border border-border overflow-hidden hover:shadow-md transition-shadow h-full flex flex-col">
        <div className="relative aspect-[4/3] bg-muted overflow-hidden">
          {listing.images[0] ? (
            <img
              src={listing.images[0]}
              alt={listing.title}
              className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
            />
          ) : (
            <div className="w-full h-full flex items-center justify-center text-muted-foreground">
              <Gauge className="w-12 h-12" />
            </div>
          )}
          {listing.isFeatured && (
            <Badge className="absolute top-2 left-2 bg-accent text-white border-0">
              Featured
            </Badge>
          )}
          <Badge
            variant={listing.condition === 'NEW' ? 'success' : 'secondary'}
            className="absolute top-2 right-2"
          >
            {listing.condition === 'NEW' ? 'New' : 'Used'}
          </Badge>
          <button
            onClick={handleFavoriteClick}
            className="absolute bottom-2 right-2 p-2 rounded-full bg-white/90 opacity-0 group-hover:opacity-100 transition-opacity hover:bg-white"
          >
            <Heart
              className={cn(
                'w-4 h-4 transition-colors',
                favorited ? 'fill-red-500 text-red-500' : 'text-foreground'
              )}
            />
          </button>
        </div>
        <div className="p-4 flex flex-col flex-1">
          <h3 className="font-semibold text-foreground group-hover:text-primary transition-colors line-clamp-2 text-sm leading-snug">
            {listing.title}
          </h3>
          <p className="text-lg font-bold text-accent mt-2">
            {formattedPrice || 'Price on request'}
          </p>
          <div className="flex items-center gap-2 mt-2 text-xs text-muted-foreground flex-wrap">
            <span className="flex items-center gap-1">
              <Calendar className="w-3 h-3" />
              {listing.year}
            </span>
            {listing.mileage != null && (
              <>
                <span className="text-border">|</span>
                <span className="flex items-center gap-1">
                  <Gauge className="w-3 h-3" />
                  {listing.mileage.toLocaleString()} km
                </span>
              </>
            )}
            {listing.fuelType && (
              <>
                <span className="text-border">|</span>
                <span className="flex items-center gap-1">
                  <Fuel className="w-3 h-3" />
                  {listing.fuelType}
                </span>
              </>
            )}
          </div>
          <div className="flex items-center gap-1 mt-auto pt-3 text-xs text-muted-foreground">
            <MapPin className="w-3 h-3 flex-shrink-0" />
            <span className="truncate">
              {listing.location.city}, {listing.location.country}
            </span>
          </div>
          <p className="text-xs text-muted-foreground mt-1">{listing.seller.name}</p>
        </div>
      </div>
    </Link>
  );
}
