// frontend/app/pages/terms.vue
<template>
  <div>
    <section class="bg-navy text-white py-12">
      <div class="container mx-auto px-4">
        <h1 class="text-3xl font-bold">Terms of Service</h1>
        <p class="text-gray-300 mt-2">Last updated: February 14, 2026</p>
      </div>
    </section>

    <div class="container mx-auto px-4 py-12">
      <div class="max-w-3xl mx-auto prose prose-navy">
        <div class="space-y-8 text-gray-600 leading-relaxed">
          <section>
            <h2 class="text-xl font-bold text-navy mb-3">1. Acceptance of Terms</h2>
            <p>By accessing and using the MenonTrucks website and services ("Service"), you accept and agree to be bound by the terms and provisions of this agreement. If you do not agree to abide by these terms, please do not use this Service.</p>
          </section>

          <section>
            <h2 class="text-xl font-bold text-navy mb-3">2. Description of Service</h2>
            <p>MenonTrucks provides an online marketplace platform that connects buyers and sellers of commercial vehicles, equipment, and parts. We do not directly sell, buy, or own any of the vehicles listed on our platform. MenonTrucks acts solely as an intermediary facilitating communication between buyers and sellers.</p>
          </section>

          <section>
            <h2 class="text-xl font-bold text-navy mb-3">3. User Accounts</h2>
            <p>To access certain features of the Service, you must register for an account. You agree to provide accurate, current, and complete information during registration and to update such information to keep it accurate, current, and complete. You are responsible for safeguarding your account password and for all activities that occur under your account.</p>
          </section>

          <section>
            <h2 class="text-xl font-bold text-navy mb-3">4. Listings</h2>
            <p>Sellers are responsible for the accuracy of their listings. All listings must comply with applicable laws and regulations. MenonTrucks reserves the right to remove any listing that violates these terms or is deemed inappropriate.</p>
            <ul class="list-disc pl-6 mt-2 space-y-1">
              <li>Listings must be for genuine commercial vehicles, equipment, or parts</li>
              <li>All information provided must be accurate and not misleading</li>
              <li>Images must be of the actual item being sold</li>
              <li>Pricing must be clearly stated and accurate</li>
            </ul>
          </section>

          <section>
            <h2 class="text-xl font-bold text-navy mb-3">5. Prohibited Activities</h2>
            <p>You agree not to engage in any of the following prohibited activities:</p>
            <ul class="list-disc pl-6 mt-2 space-y-1">
              <li>Posting false, misleading, or fraudulent listings</li>
              <li>Impersonating any person or entity</li>
              <li>Using the Service for any illegal purpose</li>
              <li>Attempting to interfere with the proper functioning of the Service</li>
              <li>Scraping, data mining, or similar data collection activities</li>
              <li>Sending unsolicited communications to other users</li>
            </ul>
          </section>

          <section>
            <h2 class="text-xl font-bold text-navy mb-3">6. Limitation of Liability</h2>
            <p>MenonTrucks is not responsible for any transactions between buyers and sellers. We do not guarantee the quality, safety, or legality of items listed, the truth or accuracy of listings, or the ability of sellers to sell items or buyers to pay for items. MenonTrucks shall not be liable for any indirect, incidental, special, consequential, or punitive damages.</p>
          </section>

          <section>
            <h2 class="text-xl font-bold text-navy mb-3">7. Intellectual Property</h2>
            <p>The Service and its original content, features, and functionality are and will remain the exclusive property of MenonTrucks GmbH. The Service is protected by copyright, trademark, and other laws of Germany and foreign countries.</p>
          </section>

          <section>
            <h2 class="text-xl font-bold text-navy mb-3">8. Termination</h2>
            <p>We may terminate or suspend your account and access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach these Terms.</p>
          </section>

          <section>
            <h2 class="text-xl font-bold text-navy mb-3">9. Governing Law</h2>
            <p>These Terms shall be governed and construed in accordance with the laws of Germany, without regard to its conflict of law provisions. Any disputes arising from these Terms shall be subject to the exclusive jurisdiction of the courts located in Munich, Germany.</p>
          </section>

          <section>
            <h2 class="text-xl font-bold text-navy mb-3">10. Contact Us</h2>
            <p>If you have any questions about these Terms, please contact us at:</p>
            <p class="mt-2">
              MenonTrucks GmbH<br />
              Email: legal@menontrucks.com<br />
              Address: Hauptstrasse 42, 80331 Munich, Germany
            </p>
          </section>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
useHead({
  title: 'Terms of Service - MenonTrucks',
  meta: [
    { name: 'description', content: 'Read the MenonTrucks Terms of Service. Understand our rules and guidelines for using the commercial vehicle marketplace.' },
  ],
})
</script>

// apps/web/src/app/(main)/terms/page.tsx
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | Menon Mobility',
  description: 'Terms of Service for using the Menon Mobility marketplace.',
};

export default function TermsPage() {
  return (
    <div className="bg-background min-h-screen">
      <div className="bg-gradient-to-br from-primary to-primary-950 text-white py-12">
        <div className="container mx-auto px-4">
          <h1 className="text-3xl font-bold">Terms of Service</h1>
          <p className="text-white/70 mt-2">Last updated: January 15, 2024</p>
        </div>
      </div>
      <div className="container mx-auto px-4 py-12">
        <div className="max-w-3xl mx-auto prose prose-sm prose-gray">
          <div className="bg-white rounded-xl border border-border p-8 space-y-6">
            <section>
              <h2 className="text-xl font-bold text-foreground mb-3">1. Acceptance of Terms</h2>
              <p className="text-muted-foreground leading-relaxed">
                By accessing or using the Menon Mobility platform (&quot;Service&quot;), you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not use the Service. These terms apply to all visitors, users, and others who access or use the Service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-foreground mb-3">2. Description of Service</h2>
              <p className="text-muted-foreground leading-relaxed">
                Menon Mobility provides an online marketplace platform for buying and selling commercial vehicles, including but not limited to trucks, trailers, construction equipment, vans, and related parts and accessories. We act as an intermediary connecting buyers and sellers and do not own, sell, or purchase any vehicles listed on the platform.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-foreground mb-3">3. User Accounts</h2>
              <p className="text-muted-foreground leading-relaxed">
                When you create an account, you must provide accurate and complete information. You are responsible for safeguarding the password and for all activities that occur under your account. You must notify us immediately of any unauthorized use of your account. We reserve the right to suspend or terminate accounts that violate these terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-foreground mb-3">4. Listings and Transactions</h2>
              <p className="text-muted-foreground leading-relaxed">
                Sellers are solely responsible for the accuracy of their listings, including descriptions, images, pricing, and availability. Menon Mobility does not guarantee the quality, safety, or legality of listed items. All transactions are conducted directly between buyers and sellers. We encourage buyers to inspect vehicles in person before completing a purchase.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-foreground mb-3">5. Fees and Payments</h2>
              <p className="text-muted-foreground leading-relaxed">
                Certain features of the Service require payment of fees, including subscription plans and featured listings. All fees are stated in Euros (EUR) unless otherwise specified. Fees are non-refundable except as required by applicable law. We reserve the right to change our pricing at any time with reasonable notice to users.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-foreground mb-3">6. Prohibited Conduct</h2>
              <p className="text-muted-foreground leading-relaxed">
                Users may not: (a) post false, misleading, or fraudulent listings; (b) use the Service for any illegal purpose; (c) harass, abuse, or harm other users; (d) attempt to circumvent any security features; (e) scrape or collect data from the Service without permission; (f) post spam or unsolicited advertisements.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-foreground mb-3">7. Intellectual Property</h2>
              <p className="text-muted-foreground leading-relaxed">
                The Service and its original content, features, and functionality are owned by Menon Mobility and are protected by international copyright, trademark, and other intellectual property laws. Users retain ownership of content they submit but grant us a non-exclusive license to use, display, and distribute such content on the platform.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-foreground mb-3">8. Limitation of Liability</h2>
              <p className="text-muted-foreground leading-relaxed">
                Menon Mobility shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the Service. Our total liability shall not exceed the amount paid by you to Menon Mobility in the twelve months preceding the claim.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-foreground mb-3">9. Governing Law</h2>
              <p className="text-muted-foreground leading-relaxed">
                These Terms shall be governed by the laws of the European Union and the applicable national law of the Netherlands. Any disputes shall be subject to the exclusive jurisdiction of the courts in Amsterdam, the Netherlands.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-foreground mb-3">10. Contact</h2>
              <p className="text-muted-foreground leading-relaxed">
                If you have questions about these Terms, please contact us at legal@menonmobility.com or visit our contact page.
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}
